ydataai/go-core

.github/dependabot.yaml, .github/workflows/merge_master.yaml, .github/workflows/prereleased.yaml, .github/workflows/pull_request.yaml, .github/workflows/released.yaml, Makefile
=> chore(pipelines): first iteration of the pipelines

go.mod, go.sum, pkg/common/clients/prometheus_client.go, pkg/common/clients/prometheus_client_configuration.go
- Prometheus Client
closes #19
=> feat(prometheus): prometheus client 

pkg/common/clients/storage_client.go
Defining a StorageClient interface.
closes #24
=> feat(storage): add StorageClientInterface

pkg/common/clients/storage_client.go
=> chore(storage): add path suffix as parameter

pkg/common/clients/prometheus_client.go, pkg/common/clients/storage_client.go, pkg/common/clients/vault_client.go, pkg/common/server/server.go, pkg/controllers/grpc/cloud_adapter_grpc_controller.go, pkg/controllers/rest/cloud_adapter_rest_controller.go, pkg/services/k8s/client.go
=> chore(logging): replace logrus by logger proxy 

pkg/common/clients/storage_client.go
=> chore: revert path suffix as parameter

pkg/common/logging/configuration.go, pkg/common/logging/formatter.go, pkg/common/logging/logrus.go
=> fix(logging): fix logging format

.github/workflows/merge_master.yaml, .releaserc.json
=> fix(pipelines): add tag prefix 'v' for releases 

pkg/common/server/server.go
closes [PLT-58]
[PLT-58]: https://ydata.atlassian.net/browse/PLT-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: logging when the server is running [PLT-58]

go.mod, pkg/common/grpc/logging_interceptor.go
closes [PLT-103]
[PLT-103]: https://ydata.atlassian.net/browse/PLT-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(grpc): logging interceptor 

pkg/common/grpc/logging_interceptor.go
closes [PLT-115]
[PLT-115]: https://ydata.atlassian.net/browse/PLT-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(grpc): logging error messages

pkg/common/clients/vault_client.go
closes [PLT-55]
[PLT-55]: https://ydata.atlassian.net/browse/PLT-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(vault): new login if token renew fails

pkg/common/server/server.go
closes [PLT-122]
[PLT-122]: https://ydata.atlassian.net/browse/PLT-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: move httpServer to Run method

go.mod, go.sum, pkg/common/clients/redis_client.go, pkg/common/clients/redis_configuration.go
[PLT-139]
[PLT-139]: https://ydata.atlassian.net/browse/PLT-139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(redis): client and configuration

pkg/common/clients/redis_client.go
closes [PLT-149]
[PLT-149]: https://ydata.atlassian.net/browse/PLT-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(redis-client) make sure the server is ready to write

pkg/common/clients/redis_client.go, pkg/common/clients/redis_configuration.go
[PLT-158]
[PLT-158]: https://ydata.atlassian.net/browse/PLT-158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(redis): add TLS support

pkg/common/clients/redis_client.go, pkg/common/clients/redis_configuration.go
[PLT-158]
[PLT-158]: https://ydata.atlassian.net/browse/PLT-158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(redis): add failover and TLS support

pkg/common/clients/redis_client.go
[PLT-159]
[PLT-159]: https://ydata.atlassian.net/browse/PLT-159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(redis): interface definition and default implementation

pkg/common/clients/redis_client.go, pkg/common/clients/redis_configuration.go
closes [PLT-172]
[PLT-172]: https://ydata.atlassian.net/browse/PLT-172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(redis): client with and without TLS

pkg/common/clients/redis_client.go
[PLT-190]
[PLT-190]: https://ydata.atlassian.net/browse/PLT-190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(redis): add cluster support

pkg/common/config/manager_configuration.go
[PLT-184]
[PLT-184]: https://ydata.atlassian.net/browse/PLT-184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(k8s): add webhooks config flag
